import test from 'node:test';
import assert from 'node:assert/strict';
import { summarizeCanonicalMonthlyPlan } from '../lib/production/engineering-plan-metrics.mjs';
const plan={
  total_mineral_to_plant_tons:'13000',
  total_waste_tons:'840',
  total_movement_tons:'13840',
  planned_advance_m:'254',
  planned_drilling_m:'10287',
};
const lines=[
  {line_type:'radial_drilling',planned_drilling_m:'1304'},
  {line_type:'radial_drilling',planned_drilling_m:'303'},
  {line_type:'radial_drilling',planned_drilling_m:'96'},
  {line_type:'radial_drilling',planned_drilling_m:'693'},
  {line_type:'development',planned_tons:'354',planned_advance_m:'21'},
  {line_type:'development',planned_tons:'486',planned_advance_m:'20'},
  {line_type:'mine_total',planned_tons:'7000'},
  {line_type:'transport'},
  {line_type:'transport'},
  {line_type:'mine_total',planned_tons:'6000'},
  {line_type:'preparation',planned_tons:'6550',planned_advance_m:'213'},
  {line_type:'chamber',planned_tons:'6450'},
];

test('canonical plan totals are never generated by overlapping detail line sums',()=>{
  const r=summarizeCanonicalMonthlyPlan(plan,lines,12);
  assert.equal(r.summary.plannedTons,13000);
  assert.notEqual(r.summary.plannedTons,26840);
  assert.equal(r.summary.plannedDrillingM,10287);
  assert.notEqual(r.summary.plannedDrillingM,2396);
  assert.equal(r.summary.plannedAdvanceM,254);
  assert.equal(r.summary.totalMovementTons,13840);
  assert.equal(r.summary.wasteTons,840);
  assert.equal(r.breakdown.mineTotalTons,13000);
  assert.equal(r.breakdown.radialDrillingM,2396);
  assert.equal(r.breakdown.detailedAdvanceM,254);
  assert.equal(r.breakdown.complete,true);
  assert.equal(r.breakdown.movementHeaderConsistent,true);
  assert.equal(r.breakdown.overlapsByDesign,true);
});

test('partial plan detail never presents its subtotals as complete',()=>{
  const r=summarizeCanonicalMonthlyPlan(plan,lines.slice(0,3),12);
  assert.equal(r.breakdown.complete,false);
  assert.equal(r.breakdown.radialDrillingM,null);
  assert.equal(r.breakdown.mineTotalTons,null);
  assert.equal(r.summary.plannedTons,13000);
  assert.equal(r.summary.plannedDrillingM,10287);
});

test('missing or malformed header totals do not silently turn into zero',()=>{
  const r=summarizeCanonicalMonthlyPlan({total_mineral_to_plant_tons:null,planned_drilling_m:'invalid'},[],0);
  assert.equal(r.summary.plannedTons,null);
  assert.equal(r.summary.plannedDrillingM,null);
  assert.equal(r.breakdown.movementHeaderConsistent,null);
  assert.equal(r.breakdown.complete,true);
});
test('conflicting monthly header is exposed for documentary review',()=>{
  const r=summarizeCanonicalMonthlyPlan({...plan,total_movement_tons:13900},lines,12);
  assert.equal(r.breakdown.movementHeaderConsistent,false);
  assert.equal(r.summary.totalMovementTons,13900);
});
