// Plantilla CSV de ejemplo para la importación de fichas técnicas.
// Extraída verbatim de components/maintenance/technical-sheet-import.tsx;
// el contenido de la plantilla no cambia, solo vive en su propio módulo.

export function buildTemplateCsv() {
  const headers = [
    'ASSET_CODE',
    'ASSET_NAME',
    'BRAND_NAME',
    'MODEL_NAME',
    'SOURCE_URL',
    'SOURCE_TYPE',
    'SOURCE_VERSION',
    'VALIDATED',
    'RAW_SPECS',
    'COMPONENT_CODE',
    'COMPONENT_NAME',
    'COMPONENT_LEVEL',
    'COMPONENT_CRITICALITY',
    'COMPONENT_STATUS',
    'FAULT_CODE',
    'FAULT_NAME',
    'FAULT_SEVERITY',
    'SYMPTOM',
    'CAUSE',
    'EFFECT',
    'RECOMMENDED_ACTION',
  ];

  const rows = [
    [
      'VEH-001',
      'Komatsu WA380-8',
      'Komatsu',
      'WA380-8',
      'https://www.komatsu.com/en-us/products/equipment/wheel-loaders/large-wheel-loaders/wa380-8',
      'official',
      '2026-07',
      'si',
      '{"power_kw":143,"power_hp":191,"weight_kg":19020,"bucket_m3":3.3}',
      'ENG-001',
      'Motor',
      '1',
      'alta',
      'activo',
      'ENG-001-01',
      'Sobretemperatura',
      'alta',
      'Alza rapida de temperatura y perdida de potencia',
      'Inspeccionar sistema de enfriamiento y filtros',
      'Aumento de temperatura del motor',
      'Detener, revisar y programar mantencion',
    ],
    [
      'VEH-002',
      'Cat 390F L',
      'Caterpillar',
      '390F L',
      'https://www.cat.com/en_US/products/new/equipment/excavators/large-excavators/108464.html',
      'official',
      '2026-07',
      'si',
      '{"power_hp":524,"weight_kg":87800,"bucket_m3":2.2,"dig_depth_m":10.75}',
      'HYD-001',
      'Sistema hidraulico',
      '1',
      'alta',
      'activo',
      'HYD-001-01',
      'Fuga en linea',
      'media',
      'Presión baja o rastros de aceite',
      'Revisar mangueras, sellos y acoples',
      'Perdida de presión hidráulica',
      'Aislar, reparar y probar presión',
    ],
    [
      'VEH-003',
      'Cat 324D L',
      'Caterpillar',
      '324D L',
      'https://www.miltoncat.com/machinery-equipment/new/excavators/324d-l-hydraulic-excavator',
      'official',
      '2026-07',
      'si',
      '{"power_hp":188,"weight_kg":24790,"bucket_m3":1.6,"engine":"Cat C7 ACERT"}',
      'UND-001',
      'Undercarriage',
      '1',
      'alta',
      'activo',
      'UND-001-01',
      'Desgaste de oruga',
      'media',
      'Holgura y vibracion anormal',
      'Inspeccionar rodillos, zapatas y tension',
      'Desgaste prematuro del tren de rodaje',
      'Ajustar tension y cambiar componentes desgastados',
    ],
    [
      'MCH-004',
      'Scooptram ST1030',
      'Epiroc',
      'Scooptram ST1030',
      'https://www.epiroc.com/en-us/products/loaders-and-trucks/diesel-loaders/scooptram-st1030',
      'official',
      '2026-07',
      'si',
      '{"load_ton":10,"application":"underground loading"}',
      'HDL-001',
      'Sistema de carguio',
      '1',
      'alta',
      'activo',
      'HDL-001-01',
      'Fuga hidráulica en carguio',
      'alta',
      'Perdida de fuerza o movimiento lento',
      'Revisar circuito, purgar y reemplazar elementos defectuosos',
      'Reduccion de rendimiento en carguio',
      'Aislar, revisar y reparar el circuito',
    ],
    [
      'MCH-005',
      'Boomer S1D',
      'Epiroc',
      'Boomer S1D',
      'https://www.epiroc.com/content/dam/epiroc/underground-mining-and-tunneling/tme/drilling-technical-specifications/boomer/9869_0094_01c_Boomer_S1_technical_specification_english.pdf',
      'official',
      '2026-07',
      'si',
      '{"application":"face drilling","section_m2":"33"}',
      'BOOM-001',
      'Brazo de perforacion',
      '1',
      'alta',
      'activo',
      'BOOM-001-01',
      'Juego excesivo en brazo',
      'media',
      'Deriva de posicion o imprecision',
      'Medir holguras y programar recambio de bujes o pines',
      'Menor calidad de perforacion',
      'Ajustar y calibrar brazo',
    ],
    [
      'MCH-006',
      'Cat 938H',
      'Caterpillar',
      '938H',
      'https://h-cpc.cat.com/cmms/v2?cid=406&f=product&gid=263&it=product&lid=en&nc=1&pid=17275910&sc=R160',
      'official',
      '2026-07',
      'si',
      '{"application":"loading","power_hp":"180"}',
      'HYD-001',
      'Sistema hidraulico',
      '1',
      'alta',
      'activo',
      'HYD-001-01',
      'Perdida de fuerza de levantamiento',
      'media',
      'Balde lento o poca respuesta',
      'Inspeccionar presión y componentes hidraulicos',
      'Ciclos mas largos y menor productividad',
      'Prueba hidráulica y calibracion',
    ],
    [
      'MCH-007',
      'Scooptram ST1010',
      'Epiroc',
      'ST1010',
      'https://www.epiroc.com/content/dam/epiroc/parts-and-services/service-agreements-and-audits/brochures/9865%200020%2001%20RigScan%20brochure.pdf',
      'official',
      '2026-07',
      'si',
      '{"application":"underground loading","capacity_ton":10}',
      'ENG-001',
      'Motor',
      '1',
      'alta',
      'activo',
      'ENG-001-01',
      'Falla de alimentacion',
      'alta',
      'Perdida de potencia o arranque lento',
      'Revisar combustible, filtros y presión',
      'Detencion del equipo',
      'Revisar circuito y programar mantenimiento',
    ],
    [
      'MCH-008',
      'Boomer 281',
      'Epiroc',
      'Boomer 281',
      'https://www.epiroc.com/es-cl/products/drill-rigs/face-drill-rigs/boomer-281',
      'official',
      '2026-07',
      'si',
      '{"application":"face drilling","coverage_m2":"48"}',
      'DRL-001',
      'Sistema de perforacion',
      '1',
      'alta',
      'activo',
      'DRL-001-01',
      'Baja presión de perforacion',
      'alta',
      'Bajo avance o vibracion anormal',
      'Revisar bomba, presión y circuito',
      'Rendimiento bajo',
      'Ajustar y calibrar sistema',
    ],
    [
      'MCH-009',
      'Cat 246D3',
      'Caterpillar',
      '246D3',
      'https://www.cat.com/en_GB/products/new/equipment/skid-steer-and-compact-track-loaders/skid-steer-loaders/30056688547513.html',
      'official',
      '2026-07',
      'si',
      '{"power_hp":74.3,"payload_kg":1000,"weight_kg":3392}',
      'HID-001',
      'Sistema hidraulico',
      '1',
      'alta',
      'activo',
      'HID-001-01',
      'Baja presión hidráulica',
      'alta',
      'Brazo lento o respuesta irregular',
      'Prueba de presión y revisión de mangueras',
      'Menor capacidad de trabajo',
      'Inspeccionar circuito hidraulico',
    ],
    [
      'MCH-010',
      'Cat 938G',
      'Caterpillar',
      '938G',
      'https://h-cpc.cat.com/cmms/v2?cid=406&f=product&gid=263&it=product&lid=en&nc=1&pid=752990&sc=M620',
      'official',
      '2026-07',
      'si',
      '{"power_hp":160,"application":"material handling"}',
      'ENG-001',
      'Motor',
      '1',
      'alta',
      'activo',
      'ENG-001-01',
      'Perdida de potencia',
      'media',
      'Menor fuerza y respuesta lenta',
      'Inspeccionar admision, filtros y combustible',
      'Menor productividad',
      'Revisar sistema de admision',
    ],
    [
      'MCH-010B',
      'Cat 938K',
      'Caterpillar',
      '938K',
      'https://h-cpc.cat.com/cmms/v2?cid=406&f=product&gid=263&it=product&lid=en&nc=1&pid=18263412&sc=NACD',
      'official',
      '2026-07',
      'si',
      '{"application":"loading","type":"wheel loader"}',
      'PWR-001',
      'Tren motriz',
      '1',
      'alta',
      'activo',
      'PWR-001-01',
      'Patinamiento o baja respuesta',
      'media',
      'Menor empuje o ciclos mas lentos',
      'Revisar aceite, filtros y diagnostico del tren motriz',
      'Menor productividad',
      'Inspeccionar y probar tren motriz',
    ],
    [
      'MCH-011',
      'QAS 500',
      'Atlas Copco',
      'QAS 500',
      'https://www.atlascopco.com/en-rs/construction-equipment/products/power-diesel-generators/mobile-europe/qas',
      'official',
      '2026-07',
      'si',
      '{"power_kva":500,"application":"power supply"}',
      'CTRL-001',
      'Control y proteccion',
      '1',
      'alta',
      'activo',
      'CTRL-001-01',
      'Falla de control',
      'media',
      'Salida inestable o alarmas',
      'Verificar tablero y sensores',
      'Riesgo de corte de energia',
      'Inspeccionar control y protecciones',
    ],
    [
      'MCH-012',
      'Simba S7',
      'Epiroc',
      'Simba S7',
      'https://www.epiroc.com/en-us/products/drill-rigs/production-drill-rigs/simba-s7',
      'official',
      '2026-07',
      'si',
      '{"application":"production drilling","type":"long-hole drill rig"}',
      'DRL-001',
      'Sistema de perforacion',
      '1',
      'alta',
      'activo',
      'DRL-001-01',
      'Baja presión de perforacion',
      'alta',
      'Bajo avance o vibracion anormal',
      'Revisar bombas, presión y avance',
      'Menor precision',
      'Calibrar y revisar circuito',
    ],
    [
      'MCH-013',
      'Simba 1254',
      'Epiroc',
      'Simba 1254',
      'https://www.epiroc.com/en-us/products/drill-rigs/production-drill-rigs/simba-1254',
      'official',
      '2026-07',
      'si',
      '{"application":"underground drilling","type":"production drill rig"}',
      'ELE-001',
      'Sistema electrico y control',
      '1',
      'media',
      'activo',
      'ELE-001-01',
      'Error de comunicacion',
      'media',
      'Alarmas o mandos intermitentes',
      'Inspeccionar conectores y diagnostico',
      'Paradas intermitentes',
      'Verificar control y sensores',
    ],
    [
      'MCH-014',
      'Toyota Hilux',
      'Toyota',
      'Hilux',
      'https://www.toyota.com.au/hilux',
      'official',
      '2026-07',
      'si',
      '{"application":"support","type":"pickup 4x4"}',
      'BRK-001',
      'Frenos y suspension',
      '1',
      'alta',
      'activo',
      'BRK-001-01',
      'Desgaste de frenos',
      'media',
      'Recorrido largo del pedal o vibracion',
      'Inspeccionar frenos y programar recambio',
      'Riesgo de seguridad',
      'Mantener y calibrar el sistema',
    ],
    [
      'MCH-015',
      'Liugong CPCD25A',
      'Liugong',
      'CPCD25A',
      'https://www.liugong.com/en/product/cpcd25/index.html',
      'official',
      '2026-07',
      'si',
      '{"application":"logistics","type":"forklift diesel"}',
      'HID-001',
      'Sistema hidraulico',
      '1',
      'alta',
      'activo',
      'HID-001-01',
      'Fuga o baja fuerza de levante',
      'alta',
      'Horquillas lentas o caída de carga',
      'Inspeccionar circuito y reemplazar elementos',
      'Menor productividad',
      'Revisar bomba y sellos',
    ],
    [
      'DMP-015B',
      'GHH MK-A20',
      'GHH',
      'MK-A20',
      'https://www.ghh-fahrzeuge.de/',
      'official',
      '2026-07',
      'si',
      '{"application":"acarreo subterraneo","type":"dump truck"}',
      'TRN-001',
      'Transmision',
      '1',
      'alta',
      'activo',
      'TRN-001-01',
      'Patinamiento',
      'media',
      'Perdida de fuerza o cambios bruscos',
      'Verificar aceite y diagnostico del sistema',
      'Menor productividad y mayor desgaste',
      'Mantener y ajustar',
    ],
    [
      'MCH-016',
      'Cat 320D L',
      'Caterpillar',
      '320D L',
      'https://h-cpc.cat.com/cmms/v2?cid=406&f=product&gid=329&it=product&lid=nc&nc=1&pid=18341586&sc=R760',
      'official',
      '2026-07',
      'si',
      '{"application":"excavation","type":"hydraulic excavator"}',
      'HYD-001',
      'Sistema hidraulico',
      '1',
      'alta',
      'activo',
      'HYD-001-01',
      'Perdida de presión',
      'alta',
      'Movimiento lento o irregular',
      'Prueba de presión y revisión de fugas',
      'Caida de productividad',
      'Revisar circuito hidraulico',
    ],
    [
      'MCH-017',
      'Cat 928G',
      'Caterpillar',
      '928G',
      'https://h-cpc.cat.com/cmms/v2?cid=406&f=product&gid=263&it=product&lid=en&nc=1&pid=753093&sc=US',
      'official',
      '2026-07',
      'si',
      '{"application":"loading","type":"wheel loader"}',
      'HYD-001',
      'Sistema hidraulico',
      '1',
      'alta',
      'activo',
      'HYD-001-01',
      'Baja fuerza de levantamiento',
      'media',
      'Ciclos lentos o poca respuesta',
      'Inspeccionar presión y circuito',
      'Mayor tiempo de carga',
      'Revisar bombas y filtros',
    ],
    [
      'MCH-18',
      'Cat 950 GC',
      'Caterpillar',
      '950 GC',
      'https://www.cat.com/en_US/products/new/equipment/wheel-loaders/medium-wheel-loaders/1000029532.html',
      'official',
      '2026-07',
      'si',
      '{"application":"loading","type":"wheel loader"}',
      'ENG-001',
      'Motor',
      '1',
      'alta',
      'activo',
      'ENG-001-01',
      'Falla de alimentacion',
      'media',
      'Arranque lento o perdida de potencia',
      'Revisar filtros y calidad de combustible',
      'Menor eficiencia',
      'Inspeccionar sistema de admision',
    ],
    [
      'MCH-019',
      'JCB 3CX',
      'JCB',
      '3CX',
      'https://www.jcb.com/en-gb/products/backhoe-loaders/3cx',
      'official',
      '2026-07',
      'si',
      '{"application":"excavation","type":"backhoe loader"}',
      'HYD-001',
      'Sistema hidraulico',
      '1',
      'alta',
      'activo',
      'HYD-001-01',
      'Fuga hidráulica',
      'media',
      'Respuesta lenta o perdida de fuerza',
      'Revisar fugas y presión',
      'Baja capacidad operacional',
      'Inspeccionar circuito hidraulico',
    ],
    [
      'MCH-020',
      'JCB 531-70',
      'JCB',
      '531-70',
      'https://www.jcb.com/en-gb/products/loadall-telehandlers/531-70',
      'official',
      '2026-07',
      'si',
      '{"application":"lifting","type":"telehandler"}',
      'BOOM-001',
      'Brazo telescopico',
      '1',
      'alta',
      'activo',
      'BOOM-001-01',
      'Holgura o desalineacion',
      'media',
      'Movimiento impreciso o vibracion',
      'Inspeccionar holguras y cilindros',
      'Menor seguridad',
      'Calibrar y revisar brazo',
    ],
    [
      'MCH-021',
      'JCB 455ZX',
      'JCB',
      '455ZX',
      'https://www.jcb.com/en-gb/products/wheel-loaders/455zx',
      'official',
      '2026-07',
      'si',
      '{"application":"loading","type":"wheel loader"}',
      'ENG-001',
      'Motor',
      '1',
      'alta',
      'activo',
      'ENG-001-01',
      'Perdida de potencia',
      'media',
      'Respuesta lenta o baja fuerza',
      'Revisar filtros y admision',
      'Menor productividad',
      'Inspeccionar motor y filtros',
    ],
    [
      'MCH-022',
      'Atlas Copco XAS 97',
      'Atlas Copco',
      'XAS 97',
      'https://www.atlascopco.com/en-us/construction-equipment/products/portable-air-compressors/xas-97',
      'official',
      '2026-07',
      'si',
      '{"application":"compressed air","type":"portable compressor"}',
      'AIR-001',
      'Sistema de compresión',
      '1',
      'alta',
      'activo',
      'AIR-001-01',
      'Baja presión de aire',
      'alta',
      'Salida por debajo de lo esperado',
      'Prueba de presión y revisión de fugas',
      'Menor suministro de aire',
      'Mantener circuito y filtros',
    ],
    [
      'CMP-022B',
      'Atlas Copco XAMS 850',
      'Atlas Copco',
      'XAMS 850',
      'https://www.atlascopco.com/en-us/compressors/products/air-compressor',
      'official',
      '2026-07',
      'si',
      '{"application":"compressed air","type":"portable compressor"}',
      'AIR-001',
      'Sistema de compresión',
      '1',
      'alta',
      'activo',
      'AIR-001-01',
      'Baja presión de aire',
      'alta',
      'Salida por debajo de lo esperado',
      'Prueba de presión y revisión de fugas',
      'Menor suministro de aire',
      'Mantener circuito y filtros',
    ],
    [
      'CMP-022C',
      'Doosan XP-825',
      'Doosan Portable Power',
      'XP-825',
      'https://www.doosanportablepower.com/na/en/equipment/air-compressors/750-1600-cfm-air-compressors',
      'official',
      '2026-07',
      'si',
      '{"application":"compressed air","type":"portable compressor"}',
      'AIR-001',
      'Sistema de compresión',
      '1',
      'alta',
      'activo',
      'AIR-001-01',
      'Baja presión de aire',
      'alta',
      'Salida por debajo de lo esperado',
      'Prueba de presión y revisión de fugas',
      'Menor suministro de aire',
      'Mantener circuito y filtros',
    ],
    [
      'VEH-023',
      'Volkswagen Amarok',
      'Volkswagen',
      'Amarok',
      'https://www.volkswagen.com.au/en/models/amarok.html',
      'official',
      '2026-07',
      'si',
      '{"application":"traslado y soporte","type":"pickup 4x4"}',
      'ENG-001',
      'Motor',
      '1',
      'alta',
      'activo',
      'ENG-001-01',
      'Falla de alimentacion',
      'media',
      'Arranque lento o perdida de potencia',
      'Revisar filtro, presión y circuito de combustible',
      'Menor disponibilidad del vehiculo',
      'Revisar y programar mantencion',
    ],
    [
      'TRK-024',
      'Foton Auman 3938',
      'Foton',
      'Auman 3938',
      'https://www.fotonmotor.com/',
      'official',
      '2026-07',
      'si',
      '{"application":"transporte pesado","type":"camion tolva 6x4"}',
      'TRN-001',
      'Transmision y tren motriz',
      '1',
      'alta',
      'activo',
      'TRN-001-01',
      'Patinamiento o cambio brusco',
      'media',
      'Golpes o perdida de arrastre',
      'Verificar caja, embrague y aceite',
      'Bajo rendimiento y desgaste acelerado',
      'Ajustar y diagnosticar tren motriz',
    ],
    [
      'CMP-025',
      'Doosan P600',
      'Doosan',
      'P600',
      'https://www.doosanportablepower.com/dpp-mea/mea/en/equipment/air-compressors/medium-air-compressors',
      'official',
      '2026-07',
      'si',
      '{"application":"aire comprimido","flow_cfm":600,"pressure_bar":6.9}',
      'AIR-001',
      'Sistema de aire',
      '1',
      'alta',
      'activo',
      'AIR-001-01',
      'Baja presión o caudal',
      'alta',
      'Salida de aire irregular o caída de presión',
      'Revisar filtros, fugas y estado del airend',
      'Menor aporte a herramientas y detencion de faena',
      'Revisar circuito de aire',
    ],
    [
      'VEH-026',
      'Mitsubishi L200',
      'Mitsubishi',
      'L200',
      'https://www.mitsubishi-motors.com/en/products/l200/',
      'official',
      '2026-07',
      'si',
      '{"application":"traslado y soporte","type":"pickup 4x4"}',
      'ENG-001',
      'Motor',
      '1',
      'alta',
      'activo',
      'ENG-001-01',
      'Falla de alimentacion',
      'media',
      'Arranque lento o perdida de potencia',
      'Revisar filtro, presión y circuito de combustible',
      'Menor disponibilidad del vehiculo',
      'Revisar y programar mantencion',
    ],
    [
      'VEH-027',
      'Nissan Terrano',
      'Nissan',
      'Terrano',
      'https://www.nissan-global.com/EN/PRODUCTS/',
      'official',
      '2026-07',
      'si',
      '{"application":"traslado y soporte","type":"pickup suv 4x4"}',
      'ENG-001',
      'Motor',
      '1',
      'alta',
      'activo',
      'ENG-001-01',
      'Perdida de potencia',
      'media',
      'Aceleracion lenta o respuesta irregular',
      'Diagnosticar circuito de combustible y admision',
      'Menor disponibilidad del vehiculo',
      'Revisar y programar mantencion',
    ],
    [
      'TRK-028',
      'Ford Cargo',
      'Ford Trucks',
      'Cargo',
      'https://www.fordtrucks.com.tr/en',
      'official',
      '2026-07',
      'si',
      '{"application":"transporte de carga","type":"truck"}',
      'ENG-001',
      'Motor',
      '1',
      'alta',
      'activo',
      'ENG-001-01',
      'Perdida de potencia',
      'media',
      'Respuesta lenta o humo anormal',
      'Revisar circuito de combustible y admision',
      'Menor capacidad operacional',
      'Inspeccionar y mantener',
    ],
    [
      'TRK-029',
      'Volkswagen Constellation 15.180',
      'Volkswagen Camiones y Buses',
      'Constellation 15.180',
      'https://vwcamionesybuses.com.ar/novedad/23',
      'official',
      '2026-07',
      'si',
      '{"application":"transporte de carga","type":"camion mediano"}',
      'ENG-001',
      'Motor',
      '1',
      'alta',
      'activo',
      'ENG-001-01',
      'Perdida de potencia',
      'media',
      'Aceleracion lenta o humo anormal',
      'Revisar filtro, admision y combustible',
      'Menor disponibilidad del camion',
      'Inspeccionar y programar mantencion',
    ],
    [
      'BUS-030',
      'Volksbus',
      'Volkswagen Camiones y Buses',
      'Volksbus',
      'https://vwcamionesybuses.com.ar/modelos',
      'official',
      '2026-07',
      'si',
      '{"application":"transporte de pasajeros","type":"bus"}',
      'ENG-001',
      'Motor',
      '1',
      'alta',
      'activo',
      'ENG-001-01',
      'Perdida de potencia',
      'media',
      'Respuesta lenta o humo anormal',
      'Revisar sistema de combustible y admision',
      'Menor disponibilidad del bus',
      'Mantener y calibrar',
    ],
    [
      'FORK-031',
      'Nissan FLO 2M25',
      'Nissan',
      'FLO 2M25',
      'https://global.nissannews.com/en/channels/forklift',
      'official',
      '2026-07',
      'si',
      '{"application":"movimiento de carga","type":"forklift"}',
      'HID-001',
      'Sistema hidraulico',
      '1',
      'alta',
      'activo',
      'HID-001-01',
      'Fuga o baja fuerza de levante',
      'alta',
      'Horquillas lentas o caída de carga',
      'Inspeccionar circuito y reemplazar elementos',
      'Riesgo operacional y menor productividad',
      'Revisar y ajustar',
    ],
    [
      'VEH-032',
      'Ford F-150',
      'Ford',
      'F-150',
      'https://www.ford.com/f-150/',
      'official',
      '2026-07',
      'si',
      '{"application":"traslado y soporte","type":"pickup 4x4"}',
      'ENG-001',
      'Motor',
      '1',
      'alta',
      'activo',
      'ENG-001-01',
      'Falla de alimentacion',
      'media',
      'Arranque lento o perdida de potencia',
      'Revisar filtros y circuito de combustible',
      'Menor disponibilidad del vehiculo',
      'Revisar y programar mantencion',
    ],
    [
      'TRK-033',
      'Ford Cargo',
      'Ford Trucks',
      'Cargo',
      'https://www.fordtrucks.com.tr/en',
      'official',
      '2026-07',
      'si',
      '{"application":"transporte de carga","type":"truck"}',
      'ENG-001',
      'Motor',
      '1',
      'alta',
      'activo',
      'ENG-001-01',
      'Perdida de potencia',
      'media',
      'Respuesta lenta o humo anormal',
      'Revisar circuito de combustible y admision',
      'Menor capacidad operacional',
      'Inspeccionar y mantener',
    ],
    [
      'TRK-034',
      'Volkswagen Constellation 15.180',
      'Volkswagen Camiones y Buses',
      'Constellation 15.180',
      'https://vwcamionesybuses.com.ar/novedad/23',
      'official',
      '2026-07',
      'si',
      '{"application":"transporte de carga","type":"camion mediano"}',
      'ENG-001',
      'Motor',
      '1',
      'alta',
      'activo',
      'ENG-001-01',
      'Perdida de potencia',
      'media',
      'Aceleracion lenta o humo anormal',
      'Revisar filtro, admision y combustible',
      'Menor disponibilidad del camion',
      'Inspeccionar y programar mantencion',
    ],
    [
      'BUS-035',
      'Volksbus',
      'Volkswagen Camiones y Buses',
      'Volksbus',
      'https://vwcamionesybuses.com.ar/modelos',
      'official',
      '2026-07',
      'si',
      '{"application":"transporte de pasajeros","type":"bus"}',
      'ENG-001',
      'Motor',
      '1',
      'alta',
      'activo',
      'ENG-001-01',
      'Perdida de potencia',
      'media',
      'Respuesta lenta o humo anormal',
      'Revisar sistema de combustible y admision',
      'Menor disponibilidad del bus',
      'Mantener y calibrar',
    ],
    [
      'SND-036',
      'MDS-141',
      'MDS',
      'MDS-141',
      'https://www.epiroc.com/en-us/products/drill-rigs/exploration-drill-rigs/core-drilling-rigs',
      'official',
      '2026-07',
      'si',
      '{"application":"perforacion de exploracion","type":"core drill rig"}',
      'DRL-001',
      'Sistema de perforacion',
      '1',
      'alta',
      'activo',
      'DRL-001-01',
      'Perdida de torque',
      'media',
      'Menor avance o atascos',
      'Revisar sistema hidraulico y cabezal',
      'Baja velocidad de sondaje',
      'Revisar y calibrar',
    ],
    [
      'SND-037',
      'Ingetrol H-600',
      'Ingetrol',
      'H-600',
      'https://www.construex.com.mx/exhibidores/ingetrol/productos',
      'official',
      '2026-07',
      'si',
      '{"application":"perforacion subterranea","type":"core drilling rig"}',
      'DRL-001',
      'Sistema de perforacion',
      '1',
      'alta',
      'activo',
      'DRL-001-01',
      'Baja presión de perforacion',
      'alta',
      'Bajo avance o vibracion anormal',
      'Revisar presión y elementos del circuito',
      'Menor velocidad de perforacion',
      'Inspeccionar y calibrar',
    ],
    [
      'MCH-028',
      'Volvo L120F',
      'Volvo',
      'L120F',
      'https://www.volvoce.com/global/en/products/wheel-loaders/l120f/',
      'official',
      '2026-07',
      'si',
      '{"application":"carguio y movimiento","type":"wheel loader"}',
      'HYD-001',
      'Sistema hidraulico',
      '1',
      'alta',
      'activo',
      'HYD-001-01',
      'Baja presión hidráulica',
      'media',
      'Brazo lento o respuesta irregular',
      'Revisar circuito hidraulico y bomba',
      'Menor productividad y ciclos mas largos',
      'Inspeccionar y calibrar',
    ],
    [
      'GEN-029',
      'FG Wilson P500-3',
      'FG Wilson',
      'P500-3',
      'https://www.fgwilson.com/en_GB/products/new/fg-wilson/diesel-generators/medium-range-225-938-kva/1000012492.html',
      'official',
      '2026-07',
      'si',
      '{"application":"respaldo electrico","type":"generator"}',
      'ENG-001',
      'Motor',
      '1',
      'alta',
      'activo',
      'ENG-001-01',
      'No arranca',
      'alta',
      'El grupo no toma carga o demora en arrancar',
      'Revisar baterias, combustible y sistema de control',
      'Perdida de respaldo electrico',
      'Revisar y programar mantencion',
    ],
    [
      'GEN-030',
      'Atlas Copco QAS 275',
      'Atlas Copco',
      'QAS 275',
      'https://www.atlascopco.com/en-au/construction-equipment/products/power-connect/generators/diesel-generators/qas-275',
      'official',
      '2026-07',
      'si',
      '{"application":"respaldo electrico","type":"generator"}',
      'CTR-001',
      'Control y monitoreo',
      '1',
      'media',
      'activo',
      'CTR-001-01',
      'Alarmas o lecturas erraticas',
      'media',
      'Lecturas inestables o alarmas inesperadas',
      'Verificar sensores, cableado y setpoints',
      'Mala supervision operacional',
      'Revisar y calibrar',
    ],
    [
      'CMP-031',
      'Sullair 185',
      'Sullair',
      '185',
      'https://america.sullair.com/es/products/compresor-portatil-de-tornillo-rotativo-modelo-185-de-nivel-3-version-internacional',
      'official',
      '2026-07',
      'si',
      '{"application":"aire comprimido","flow_cfm":185,"pressure_psi":100}',
      'AIR-001',
      'Sistema de aire',
      '1',
      'alta',
      'activo',
      'AIR-001-01',
      'Baja presión o caudal',
      'alta',
      'Caida de presión o salida irregular',
      'Revisar filtros, fugas y estado del compresor',
      'Menor entrega a herramientas y detencion',
      'Revisar circuito de aire',
    ],
    [
      'MCH-032',
      'XCMG XC928',
      'XCMG',
      'XC928',
      'https://www.xcmg.com/product/pro-detail-137506.htm',
      'official',
      '2026-07',
      'si',
      '{"application":"carguio y movimiento","type":"wheel loader"}',
      'ENG-001',
      'Motor',
      '1',
      'alta',
      'activo',
      'ENG-001-01',
      'Perdida de potencia',
      'media',
      'Menor respuesta o ciclos lentos',
      'Revisar sistema de potencia y diagnostico',
      'Menor productividad',
      'Revisar y calibrar',
    ],
    [
      'GEN-033',
      'FG Wilson P275-2',
      'FG Wilson',
      'P275-2',
      'https://www.fgwilson.com/en_GB/products/new/fg-wilson/diesel-generators/medium-range-225-938-kva/227227255580579.html',
      'official',
      '2026-07',
      'si',
      '{"application":"respaldo electrico","type":"generator"}',
      'ENG-001',
      'Motor',
      '1',
      'alta',
      'activo',
      'ENG-001-01',
      'No arranca',
      'alta',
      'El grupo no toma carga o demora en arrancar',
      'Revisar baterias, combustible y sistema de control',
      'Perdida de respaldo electrico',
      'Revisar y programar mantencion',
    ],
    [
      'GEN-034',
      'Atlas Copco QAS 500',
      'Atlas Copco',
      'QAS 500',
      'https://www.atlascopco.com/en-us/construction-equipment/pfl-landings/portable-generator',
      'official',
      '2026-07',
      'si',
      '{"application":"respaldo electrico","type":"generator"}',
      'CTR-001',
      'Control y monitoreo',
      '1',
      'media',
      'activo',
      'CTR-001-01',
      'Lecturas erraticas',
      'media',
      'Alarmas o mediciones inestables',
      'Verificar sensores, cableado y setpoints',
      'Mala supervision operacional',
      'Revisar y calibrar',
    ],
    [
      'CMP-035',
      'Sullair 375H',
      'Sullair',
      '375H',
      'https://america.sullair.com/en/products/375-series-t4f-portable-diesel-compressors',
      'official',
      '2026-07',
      'si',
      '{"application":"aire comprimido","family":"375"}',
      'AIR-001',
      'Sistema de aire',
      '1',
      'alta',
      'activo',
      'AIR-001-01',
      'Baja presión o caudal',
      'alta',
      'Caida de presión o salida irregular',
      'Revisar filtros, fugas y estado del compresor',
      'Menor entrega a herramientas y detencion',
      'Revisar circuito de aire',
    ],
    [
      'GEN-036',
      'Weichai WP4.1 33 KVA',
      'Weichai',
      'WP4.1 33 KVA',
      'https://en.weichai.com/',
      'official',
      '2026-07',
      'si',
      '{"application":"respaldo electrico","type":"generator"}',
      'ENG-001',
      'Motor',
      '1',
      'alta',
      'activo',
      'ENG-001-01',
      'Falla de arranque',
      'alta',
      'No parte o parte intermitente',
      'Revisar baterias, combustible y control',
      'Perdida de respaldo',
      'Revisar y programar mantencion',
    ],
    [
      'GEN-037',
      'Cummins C500D5P',
      'Cummins',
      'C500D5P',
      'https://www.cummins.com/en-na/generators/products/ci-500d5p',
      'official',
      '2026-07',
      'si',
      '{"application":"respaldo electrico","type":"generator"}',
      'ALT-001',
      'Alternador',
      '1',
      'media',
      'activo',
      'ALT-001-01',
      'Tension inestable',
      'media',
      'Variacion de voltaje o frecuencia',
      'Verificar regulador y bornes',
      'Riesgo para cargas sensibles',
      'Revisar y calibrar',
    ],
    [
      'GEN-038',
      'Positron 63 KVA',
      'Positrón',
      'Positron 63 KVA',
      'https://www.positron.cl/wp-content/uploads/2018/05/positron-catalogo-de-servicios.pdf',
      'official',
      '2026-07',
      'si',
      '{"application":"respaldo electrico","type":"generator"}',
      'ENG-001',
      'Motor',
      '1',
      'alta',
      'activo',
      'ENG-001-01',
      'Falla de arranque',
      'alta',
      'No parte o parte intermitente',
      'Revisar baterias, combustible y control',
      'Perdida de respaldo',
      'Revisar y programar mantencion',
    ],
    [
      'GEN-039',
      'Positron 150 KVA',
      'Positrón',
      'Positron 150 KVA',
      'https://www.positron.cl/wp-content/uploads/2018/05/positron-catalogo-de-servicios.pdf',
      'official',
      '2026-07',
      'si',
      '{"application":"respaldo electrico","type":"generator"}',
      'ALT-001',
      'Alternador',
      '1',
      'media',
      'activo',
      'ALT-001-01',
      'Tension inestable',
      'media',
      'Variacion de voltaje o frecuencia',
      'Verificar regulador y bornes',
      'Riesgo para cargas sensibles',
      'Revisar y calibrar',
    ],
    [
      'GEN-039B',
      'TDB 150 KVA',
      'TDB',
      '150 KVA',
      'https://target-generators.com/product/robust-150kva-standby-generator-baudouin-engine-target-power-tb150/',
      'local-reference',
      '2026-07',
      'si',
      '{"application":"respaldo electrico","type":"generator set"}',
      'ENG-001',
      'Motor',
      '1',
      'alta',
      'activo',
      'ENG-001-01',
      'Falla de arranque',
      'alta',
      'No parte o parte intermitente',
      'Revisar baterias, combustible y control',
      'Perdida de respaldo',
      'Revisar y programar mantencion',
    ],
    [
      'GEN-040',
      'Weichai WP7 165 KVA',
      'Weichai',
      'WP7 165 KVA',
      'https://en.weichai.com/',
      'official',
      '2026-07',
      'si',
      '{"application":"respaldo electrico","type":"generator"}',
      'ENG-001',
      'Motor',
      '1',
      'alta',
      'activo',
      'ENG-001-01',
      'Falla de arranque',
      'alta',
      'No parte o parte intermitente',
      'Revisar baterias, combustible y control',
      'Perdida de respaldo',
      'Revisar y programar mantencion',
    ],
    [
      'GEN-041',
      'Weichai WP4.1 70 KVA',
      'Weichai',
      'WP4.1 70 KVA',
      'https://en.weichai.com/',
      'official',
      '2026-07',
      'si',
      '{"application":"respaldo electrico","type":"generator"}',
      'ALT-001',
      'Alternador',
      '1',
      'media',
      'activo',
      'ALT-001-01',
      'Tension inestable',
      'media',
      'Variacion de voltaje o frecuencia',
      'Verificar regulador y bornes',
      'Riesgo para cargas sensibles',
      'Revisar y calibrar',
    ],
    [
      'GEN-042',
      'Atlas Copco QAS 325 VD',
      'Atlas Copco',
      'QAS 325 VD',
      'https://www.atlascopco.com/en-au/construction-equipment/products/power-connect/generators/diesel-generators/qas-275',
      'official',
      '2026-07',
      'si',
      '{"application":"respaldo electrico","type":"generator"}',
      'CTR-001',
      'Control y monitoreo',
      '1',
      'media',
      'activo',
      'CTR-001-01',
      'Lecturas erraticas',
      'media',
      'Alarmas o mediciones inestables',
      'Verificar sensores, cableado y setpoints',
      'Mala supervision operacional',
      'Revisar y calibrar',
    ],
    [
      'VEH-043',
      'Mitsubishi Fuso Canter',
      'Mitsubishi Fuso',
      'Canter',
      'https://www.mitsubishi-fuso.com/en/product/fuso-canter/',
      'official',
      '2026-07',
      'si',
      '{"application":"support","type":"light-duty truck"}',
      'ENG-001',
      'Motor',
      '1',
      'alta',
      'activo',
      'ENG-001-01',
      'Perdida de potencia',
      'media',
      'Respuesta lenta o humo anormal',
      'Revisar filtros, admision y sistema de inyeccion',
      'Menor capacidad operativa',
      'Mantencion preventiva y diagnostico',
    ],
    [
      'VEH-044',
      'Chevrolet NKR Euro VI',
      'Chevrolet',
      'NKR Euro VI',
      'https://www.chevrolet.cl/camiones/nkr-camion',
      'official',
      '2026-07',
      'si',
      '{"application":"support","type":"light-duty truck"}',
      'CHS-001',
      'Chasis y suspension',
      '1',
      'media',
      'activo',
      'CHS-001-01',
      'Holgura en suspension',
      'media',
      'Ruidos o inestabilidad',
      'Inspeccionar suspension y direccion',
      'Menor seguridad',
      'Ajustar y reemplazar componentes',
    ],
    [
      'VEH-045',
      'Ford Transit',
      'Ford',
      'Transit',
      'https://es.ford.com/trucks/transit-passenger-van-wagon/',
      'official',
      '2026-07',
      'si',
      '{"application":"support","type":"van"}',
      'BRK-001',
      'Frenos y suspension',
      '1',
      'alta',
      'activo',
      'BRK-001-01',
      'Freno esponjoso',
      'media',
      'Recorrido largo del pedal',
      'Purgar, revisar y reemplazar componentes',
      'Riesgo de seguridad',
      'Ajuste y prueba de ruta',
    ],
    [
      'VEH-046',
      'JCB 225 NXT',
      'JCB',
      '225 NXT',
      'https://www.jcb.com/en-SG/products/machines/tracked-excavators/225-nxt/',
      'official',
      '2026-07',
      'si',
      '{"application":"excavation","type":"tracked excavator"}',
      'HYD-001',
      'Sistema hidraulico',
      '1',
      'alta',
      'activo',
      'HYD-001-01',
      'Perdida de presión hidráulica',
      'alta',
      'Movimiento lento o irregular',
      'Prueba de presión y revisión de fugas',
      'Menor productividad',
      'Revisar circuito hidraulico',
    ],
    [
      'DRV-043',
      'Epiroc Diamec 232',
      'Epiroc',
      'Diamec 232',
      'https://www.epiroc.com/es-mx/products/drill-rigs/exploration-drill-rigs/core-drilling-rigs/diamec-232',
      'official',
      '2026-07',
      'si',
      '{"application":"core drilling","type":"surface and underground"}',
      'DRL-001',
      'Sistema de perforacion',
      '1',
      'alta',
      'activo',
      'DRL-001-01',
      'Baja presión de perforacion',
      'alta',
      'Poco avance o vibracion anormal',
      'Revisar bomba, presión y circuito',
      'Menor precision',
      'Ajustar y calibrar el sistema',
    ],
    [
      'DRV-044',
      'Sandvik DE-130',
      'Sandvik',
      'DE-130',
      'https://www.rocktechnology.sandvik/en/news-and-media/news-archive/2012/12/sandvik-expands-an-already-successful-product-line-to-include-a-certified-rig-for-high-risk-environments-/',
      'official',
      '2026-07',
      'si',
      '{"application":"exploration drilling","type":"diamond drill rig"}',
      'DRL-001',
      'Sistema de perforacion',
      '1',
      'alta',
      'activo',
      'DRL-001-01',
      'Desgaste de broca',
      'media',
      'Avance lento o torque irregular',
      'Inspeccionar broca, cabezal y lubricacion',
      'Menor rendimiento',
      'Programar cambio y calibracion',
    ],
    [
      'LDR-045',
      'Manitou MLT-X 732',
      'Manitou',
      'MLT-X 732',
      'https://mltx.manitou.com/',
      'official',
      '2026-07',
      'si',
      '{"application":"handling","type":"telehandler"}',
      'TRN-001',
      'Motor y tracción',
      '1',
      'media',
      'activo',
      'TRN-001-01',
      'Perdida de fuerza',
      'media',
      'Respuesta lenta o tracción irregular',
      'Revisar filtros, aceite y transmision',
      'Menor capacidad operacional',
      'Inspeccionar y dar mantenimiento',
    ],
    [
      'EXC-046',
      'Caterpillar 320 GX',
      'Caterpillar',
      '320 GX',
      'https://www.cat.com/es_MX/products/new/equipment/excavators/medium-excavators/126506.html',
      'official',
      '2026-07',
      'si',
      '{"application":"excavation","type":"hydraulic excavator"}',
      'HYD-001',
      'Sistema hidraulico',
      '1',
      'alta',
      'activo',
      'HYD-001-01',
      'Perdida de presión',
      'alta',
      'Movimiento lento o irregular',
      'Prueba de presión y revisión de fugas',
      'Caida de productividad',
      'Revisar circuito hidraulico',
    ],
    [
      'LOD-047',
      'Caterpillar CS-533E',
      'Caterpillar',
      'CS-533E',
      'https://h-cpc.cat.com/cmms/v2?cid=406&f=product&gid=290&it=product&lid=en&nc=1&pid=18230166&sc=R160',
      'official',
      '2026-07',
      'si',
      '{"application":"compaction","type":"soil compactor"}',
      'TRL-001',
      'Sistema de compactacion',
      '1',
      'media',
      'activo',
      'TRL-001-01',
      'Baja vibracion',
      'media',
      'Compactacion deficiente o irregular',
      'Inspeccionar sistema vibratorio',
      'Menor calidad de compactacion',
      'Ajustar y probar equipo',
    ],
    [
      'TEL-048',
      'JCB 533-105',
      'JCB',
      '533-105',
      'https://www.jcb.com/es-CL/products/maquinas/telescopic-handlers/533-105/',
      'official',
      '2026-07',
      'si',
      '{"application":"lifting","type":"telehandler"}',
      'ARM-001',
      'Pluma y estabilizadores',
      '1',
      'alta',
      'activo',
      'ARM-001-01',
      'Desalineacion de pluma',
      'media',
      'Movimiento irregular o perdida de alcance',
      'Inspeccionar cilindros, bujes y fijaciones',
      'Menor precision y seguridad',
      'Ajustar y calibrar',
    ],
    [
      'SON-049',
      'Hagby Onram 1000/3',
      'Hagby',
      'Onram 1000/3',
      'https://dasmithdrilling.com/equipment/hagby-onram-10003-msha-permissible-diamond-core-drill',
      'official',
      '2026-07',
      'si',
      '{"application":"diamond drilling","type":"core drill"}',
      'DRL-001',
      'Cabezal de perforacion',
      '1',
      'alta',
      'activo',
      'DRL-001-01',
      'Perdida de torque',
      'media',
      'Menor avance o atascos',
      'Revisar desgaste mecánico y presión',
      'Caida de rendimiento',
      'Inspeccionar y lubricar',
    ],
    [
      'OTR-050',
      'Paus RL-852',
      'Paus',
      'RL-852',
      'https://www.paus.de/fileadmin/user_upload/Paus/Dokumente/Gebrauchtmaschinen/Berg-und-Tunnelbau/Gebrauchtmaschinen_BBM_RL_852_122021.pdf',
      'official',
      '2026-07',
      'si',
      '{"application":"mine support","type":"special utility"}',
      'CTR-001',
      'Control y monitoreo',
      '1',
      'media',
      'activo',
      'CTR-001-01',
      'Lectura inestable',
      'media',
      'Alarmas o mediciones inconsistentes',
      'Revisar sensores y cableado',
      'Mala supervision operacional',
      'Calibrar y verificar',
    ],
  ];

  return [headers, ...rows]
    .map((row) => row.map((value) => `"${String(value).replace(/"/g, '""')}"`).join(';'))
    .join('\n');
}
